export const RENAME_CARD_REQUEST = 'RENAME_CARD_REQUEST';
export const RENAME_CARD_SUCCESS = 'RENAME_CARD_SUCCESS';
export const RENAME_CARD_CANCELED = 'RENAME_CARD_CANCELED';

export const DELETE_CARD = 'DELETE_CARD';
