export const RENAME_LIST_REQUEST = 'RENAME_LIST_REQUEST';
export const RENAME_LIST_SUCCESS = 'RENAME_LIST_SUCCESS';
export const RENAME_LIST_CANCELED = 'RENAME_LIST_CANCELED';

export const DELETE_LIST = 'DELETE_LIST';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_CANCELED = 'ADD_CARD_CANCELED';

export const MOVE_LIST = 'MOVE_LIST';